# POST http://localhost:3000/registrar
# Content-Type: application/json

# {
#   "nombre": "franco buenas nuevas   ",
#   "email": "franco@example.com",
#   "edad": 24
# }


PUT http://localhost:3000/user
Content-Type: application/json
{"firstName": "manuel" , "lastName":"Echegaray" }



